services:
    Lens\Bundle\KiyohBundle\Inviter\Inviter:
        arguments: [ '@Symfony\Contracts\HttpClient\HttpClientInterface', '@Psr\Log\LoggerInterface', [] ]

    Lens\Bundle\KiyohBundle\Statistics\StatisticsRequest:
        arguments: [ '@Symfony\Contracts\Cache\CacheInterface', '@Symfony\Contracts\HttpClient\HttpClientInterface', [] ]

    Lens\Bundle\KiyohBundle\Kiyoh:
        arguments: [ '@Lens\Bundle\KiyohBundle\Statistics\StatisticsRequest', '@Lens\Bundle\KiyohBundle\Inviter\Inviter' ]

    Lens\Bundle\KiyohBundle\Command\UpdateKiyohStatisticsCommand:
        arguments: [ '@Lens\Bundle\KiyohBundle\Statistics\StatisticsRequest' ]
        tags: [ console.command ]
